private/build-source-tarball: add newline after the “internal error …” message.

diff --git a/private/build-and-test b/private/build-and-test
--- a/private/build-and-test
+++ b/private/build-and-test
@@ -32,7 +32,7 @@ do
         -h|--help) usage; exit 0;;
         --no-build) opt_build=; shift;;
         --) shift; break;;
-        *) printf '%s: internal error (%s)' "$0" "$1" >&2; exit 1;;
+        *) printf '%s: internal error (%s)\n' "$0" "$1" >&2; exit 1;;
     esac
 done
 
